spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hardy_spring
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  thymeleaf:
    cache: false
  mvc:
    format:
      date: yyyy-MM-dd
  mail:
    host: smtp.gmail.com
    port: 587
    username: asistente.hardy@gmail.com
    password: asistente-hardy9
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
          ssl:
            trust: smtp.gmail.com
logging:
  level:
    org:
      springframework:
        web: debug
my:
    property: C:\Users\Andrea\Documents\NetBeansProjects\Proyecto-Final\src\main\resources\static\upload
    #C:\Users\PC\OneDrive\Escritorio\nuevo nuevo\ProyectoFinalEGGAplicacionWebHardy\src\main\resources\static\upload
    #C:\Users\JunioAbril\Desktop\GG\SPRING\ProyectoFinalEGGAplicacionWebHardy\src\main\resources\static\upload
